### ISSUE TITLE
New documentation plan

### ISSUE THREAD

**Issue by laurentsigal** [waldoapp/waldo-go-agent#3]
I think we have a lot of back and forth about the documentation of the waldo-cli and this is making it very painful.

Let's move to:
- Readme is the source of truth for the public CLI documentation. It should roughly have all the documentation that currently exists in https://github.com/waldoapp/waldo-go-cli ; and Readme should reference to that repo at the top: `all the source is public, check it out at https://github.com/waldoapp/waldo-go-cli`.
- we should remove the sections of the product about CI integration. And make sure to redirect `https://app.waldo.com/applications/app-xxx/docs` to the proper Readme section
- we should remove all documentation from Waldo-go-cli. It should simply state: `Documentation for how to integrate this plugin can be found in ${readmeUrl}`.
- We should add a link at the top of the builds page to the Readme section: "Learn how to integrate your CI".
- It seems like there is a way to auto fill in a token in Readme when it's added in the query params. The link from above should include the proper token from the app so that the users can see a auto-generated doc that corresponds to their app credentials.
- the documentation in Readme should only include information that are useful to our customers. specifically we can remove all mentions of real device from there
- we can use this repo waldo-go-agent to keep track of internal documentation

**Comment by manoufeb** [comment]
It's exactly the plan I'm doing so LGTM 😅

**Comment by eBardX** [comment]
I’m OK with it. I’m not quite clear on 2 things:
1. Exactly where in readme this should live (perhaps @manoufeb can put a placeholder doc there).
2. How to autofill the upload token. (Is there a way to provide a fake upload token in case someone comes to the doc from outside the product?)

**Comment by manoufeb** [comment]
Thanks, @eBardX for taking care of this. ❤️
Here is the structure I see

- Builds & CI/CD
   - iOS - CI Upload
      - Bitrise
      - Fastlane
      - GitHub Action
      - ...
    - Android - CI Upload
      - Bitrise
      - Fastlane
      - GitHub Action
      - ...
     
For the token normally yes, if you don't have the token in the URL params there is a placeholder. I'm waiting for Readme support to come back to me with a better explanation of how to do it. 

You can see an example here:
https://developer.mixpanel.com/docs/ios-objective-c-quickstart?projectToken=Hello_John_From_Waldo

**Comment by eBardX** [comment]
Is that `Builds & CI/CD` section what is currently called just `Build` now?

**Comment by manoufeb** [comment]
Yes

**Comment by eBardX** [comment]
ok, I will make the changes, but leave them unpublished until we have clarity on the upload token.

**Comment by eBardX** [comment]
@manoufeb I have largely finished the docs. I figured out how to define a variable and provide a default value. The variable is called `waldoUploadToken`. However, I have not yet figured out how to substitute from the URL. There must be some other magic I am missing.

Two outstanding issues (besides that):

1. Not sure how to reconcile the instructions on the (existing) `Upload a new build` page with those of the (new) `iOS | Uploading your simulator build to Waldo` and `Android | Uploading your emulator build to Waldo` pages.
2. Not quite sure where to put this: https://github.com/waldoapp/waldo-go-cli/blob/master/RUNS.md

**Comment by manoufeb** [comment]
For the upload token Readme.com answered me this:
```Hi Manou, thanks for reaching out to us! My name is Tommy and I'm a support engineer here at ReadMe.
The example you see implemented by Mixpanel is actually custom developed and not a ReadMe feature. 
Generally speaking, to pass user data into ReadMe you'll need to provide it via JSON Web Token, take a look at our custom login documentation for details:
https://docs.readme.com/docs/custom-login-with-readme
https://docs.readme.com/docs/passing-data-to-jwt#user-data-json-format
I hope you find this information helpful! Please let me know if you have any other questions!```

Can you have a look and let me know if we can do it or not?

1. Can we do a manual export simulator build  page under `iOS | Uploading your simulator build to Waldo` & `Android | Uploading your emulator build to Waldo`

2. I think it's covered in the rules section. Can you confirm @laurentsigal ?
![image](https://user-images.githubusercontent.com/19815229/173636591-b21d533a-c35a-465e-917c-7b0afbfebb64.png)

**Comment by eBardX** [comment]
I’ll take a look at the customized solution, but it may be above my pay grade.

As for the other 2 items:
1. I think @laurentsigal is of the opinion that we should just nuke this: https://docs.waldo.com/docs/uploading-a-new-build
2. You are correct that in the product, the rules section self-documents nicely. However, the screenshot in the ReadMe docs (https://docs.waldo.com/docs/run-rules) shows incorrect command line syntax and so should be replaced.

**Comment by manoufeb** [comment]
I'll upload a new screenshot for 2.

**Comment by eBardX** [comment]
Yeah, that JWT stuff will need to be handled on the backend so that when a customer follows a link from the product to the docs, the customer is logged in and their upload token (or anything else) is passed along. I _believe_ the use of `<<waldoUploadToken>>` in the new docs is all that is necessary on that side of things. I’ve already provided a default value for it that works great.

**Comment by manoufeb** [comment]
@laurentsigal is that something we can easily do or it's not something we want to prioritize?
https://docs.readme.com/docs/custom-login-with-readme
https://docs.readme.com/docs/passing-data-to-jwt#user-data-json-format

**Comment by laurentsigal** [comment]
I think this is something that we should easily be able to add in webapp, see https://github.com/waldoapp/webapp/issues/3868

**Comment by manoufeb** [comment]
@eBardX can you close this one since the following work is on [webapp#3868](https://github.com/waldoapp/webapp/issues/3868), please.
I don't have access to that repo so I can't close it 😅
